version: '3.8'

services:
  version-tracker:
    build: .
    container_name: version-tracker
    ports:
      - "5556:5000"
    volumes:
      - ./config.yml:/app/config.yml:ro
    restart: unless-stopped
